---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.directory_name}}
  labels:
    app: {{cookiecutter.directory_name}}
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: {{cookiecutter.directory_name}}
